# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b19be18c0b55cec6fa501320ca4e8d112acdca6fe7f8e18e64c08f01615f60ded4703ef75f9132272a03972ef75c6ab03c7b2f9d9134db31f2a72830470b77e

test:
  secret_key_base: 6a69c38e81ccb1da69acc5e5cc70089a3aa5325201588688e1405947117e61d52529d6a1df1c4c1fca7e8f9bad26499e029148d5cbf68db4c14fe9636d918be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
