# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffebc815d925c9dd511662e64b2f3aed3e993dae040ec3cca9a8ea844601d9b957333dc8970920fd6aff39d28f853eda4dbb3bb54814eccf30baa3cd2a382fd1

test:
  secret_key_base: a0fddc24741be4ca2ba4451d0772bcf486aba5e6024fabab8577d7442e99ace6e75540bc34d16c4da2419637072137d904cb1565c049c16b95ff638cc4f5226d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
